# Generated by Django 2.0.2 on 2018-02-23 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exercicio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Cogigo exercicio')),
                ('data_inicio', models.DateField(verbose_name='Data inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mandato', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo Mandato')),
                ('nome_legislatura', models.CharField(max_length=100, verbose_name='Nome legislatura')),
                ('numero_legislatura', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo legislatura')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
            ],
        ),
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_parlamentar', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_do_parlamentar', models.CharField(max_length=100, verbose_name='Nome do parlamentar')),
                ('nome_completo_do_parlamentar', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('sexo_parlamentar', models.CharField(max_length=10, verbose_name='Sexo')),
                ('forma_de_tratamento', models.CharField(max_length=50, verbose_name='Forma de Tratar')),
                ('url_foto_parlamentar', models.URLField(verbose_name='Url da foto')),
                ('url_pagina_parlamentar', models.URLField(verbose_name='Url da Pagina/Site')),
                ('email_parlamentar', models.EmailField(max_length=255, verbose_name='Email')),
                ('sigla_partido_parlamentar', models.CharField(max_length=10, verbose_name='Sigla partido')),
                ('estado_parlamentar', models.CharField(max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Suplente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_participacao', models.CharField(max_length=100, verbose_name='Participação')),
                ('codigo_parlamentar', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='codigo parlamentar')),
                ('nome_parlamentar', models.CharField(max_length=100, verbose_name='Nome')),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplentes', to='core.Mandato')),
            ],
        ),
        migrations.AddField(
            model_name='mandato',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatos', to='core.Parlamentar'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='core.Mandato'),
        ),
    ]
