# Generated by Django 2.0.2 on 2018-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180223_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='codigo_exercicio',
            field=models.IntegerField(verbose_name='Cogigo exercicio'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='codigo_mandato',
            field=models.IntegerField(verbose_name='Codigo Mandato'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='numero_legislatura',
            field=models.IntegerField(verbose_name='Codigo legislatura'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='codigo_do_parlamentar',
            field=models.IntegerField(verbose_name='Codigo Parlamentar'),
        ),
        migrations.AlterField(
            model_name='suplente',
            name='codigo_suplente',
            field=models.IntegerField(verbose_name='codigo parlamentar'),
        ),
    ]
