# Generated by Django 2.0.2 on 2018-02-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180223_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='codigo_exercicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cogigo exercicio'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicio'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='mandato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='core.Mandato'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='codigo_mandato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Mandato'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='nome_legislatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome legislatura'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='numero_legislatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo legislatura'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandatos', to='core.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='codigo_do_parlamentar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Parlamentar'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='email_parlamentar',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='estado_parlamentar',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='forma_de_tratamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Tratar'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='nome_completo_do_parlamentar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='nome_do_parlamentar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do parlamentar'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='sexo_parlamentar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='sigla_partido_parlamentar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla partido'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='url_foto_parlamentar',
            field=models.URLField(blank=True, null=True, verbose_name='Url da foto'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='url_pagina_parlamentar',
            field=models.URLField(blank=True, null=True, verbose_name='Url da Pagina/Site'),
        ),
        migrations.AlterField(
            model_name='suplente',
            name='codigo_suplente',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigo parlamentar'),
        ),
        migrations.AlterField(
            model_name='suplente',
            name='descricao_participacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Participação'),
        ),
        migrations.AlterField(
            model_name='suplente',
            name='mandato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplentes', to='core.Mandato'),
        ),
        migrations.AlterField(
            model_name='suplente',
            name='nome_parlamentar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
