# Generated by Django 2.0.2 on 2018-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180223_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='uf_parlamentar',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
