# Generated by Django 2.0.2 on 2018-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180227_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislacao',
            name='mandato',
        ),
        migrations.AddField(
            model_name='mandato',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='mandato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicio'),
        ),
        migrations.AddField(
            model_name='mandato',
            name='numero_legislatura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo legislatura'),
        ),
        migrations.DeleteModel(
            name='Legislacao',
        ),
    ]
