# Generated by Django 2.0.2 on 2018-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180227_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='primeira_legislatura',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Primeira legislatura'),
        ),
        migrations.AddField(
            model_name='mandato',
            name='segunda_legislatura',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Segunda Legislatura'),
        ),
    ]
