# Generated by Django 2.0.2 on 2018-02-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180227_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandato',
            name='primeira_legislatura',
        ),
        migrations.RemoveField(
            model_name='mandato',
            name='segunda_legislatura',
        ),
    ]
