# Generated by Django 2.0.2 on 2018-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180227_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='descricao_participacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descricao participacao'),
        ),
    ]
