# Generated by Django 2.0.2 on 2018-02-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180227_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parlamentar',
            options={'verbose_name': 'Parlamentar', 'verbose_name_plural': 'Parlamentares'},
        ),
        migrations.AddField(
            model_name='exercicio',
            name='causa_afastamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Causa '),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='data_leitura',
            field=models.DateField(blank=True, null=True, verbose_name='Data Leitura'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='sigla_data_afastamento',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Causa '),
        ),
    ]
