# Generated by Django 2.0.2 on 2018-02-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180228_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='sigla_data_afastamento',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Sigla'),
        ),
    ]
